#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Distill\Cli\Command as DistillCommand;

$appVersion = '0.1';

$app = new Application('Distill CLI', $appVersion);

$app->add(new DistillCommand\ExtractCommand());
$app->add(new DistillCommand\AboutCommand($appVersion));

$app->setDefaultCommand('about');

$app->run();
